right_format = """$time"""

[aws]
disabled = true

[gcloud]
disabled = true


[character]
success_symbol = "[→](bold green)"
error_symbol = "[←](bold red)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[git_status]
staged = '[++\($count\)](green)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_branch]
format = " [$symbol$branch]($style) "

[hostname]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = false
time_format = " [ %T ]"
utc_time_offset = "+9"

[username]
disabled = true
